from faker.providers import BaseProvider


class Provider(BaseProvider):
    actors = (
        'Robert De Niro',
        'Al Pacino',
        'Tom Hanks',
        'Johnny Depp',
        'Jack Nicholson',
        'Marlon Brando',
        'Meryl Streep',
        'Leonardo DiCaprio',
        'Morgan Freeman',
        'Denzel Washington',
        'Anthony Hopkins',
        'Dustin Hoffman',
        'Clint Eastwood',
        'Brad Pitt',
        'Will Smith',
        'Russell Crowe',
        'Daniel Day Lewis',
        'Sean Penn',
        'James Stewart',
        'Paul Newman',
        'Humphrey Bogart',
        'Heath Ledger',
        'Edward Norton',
        'Tom Cruise',
        'Kate Winslet',
        'Kevin Spacey',
        'Mel Gibson',
        'Harrison Ford',
        'Matt Damon',
        'Jim Carrey',
        'Cary Grant',
        'Audrey Hepburn',
        'Bette Davis',
        'Katharine Hepburn',
        'Bruce Willis',
        'Christian Bale',
        'Julia Roberts',
        'Robert Downey Jr.',
        'Sean Connery',
        'Samuel L Jackson',
        'Laurence Olivier',
        'Robin Williams',
        'George Clooney',
        'Nicolas Cage',
        'John Wayne',
        'Cate Blanchett',
        'Robert Duvall',
        'Sandra Bullock',
        'Gregory Peck',
        'Spencer Tracy',
        'Gene Hackman',
        'Clark Gable',
        'Angelina Jolie',
        'Henry Fonda',
        'John Travolta',
        'Gary Cooper',
        'Jodie Foster',
        'Sylvester Stallone',
        'Ingrid Bergman',
        'Gary Oldman',
        'Charlie Chaplin',
        'Nicole Kidman',
        'Robert Redford',
        'Phillip Seymour Hoffman',
        'Judi Dench',
        'James Dean',
        'Adam Sandler',
        'Charlton Heston',
        'Liam Neeson',
        'Christopher Walken',
        'Ian McKellen',
        'Michael Caine',
        'Hugh Jackman',
        'Jack Lemmon',
        'Charlize Theron',
        'Steve McQueen',
        'Vivien Leigh',
        'Julie Andrews',
        'James Cagney',
        'Viggo Mortensen',
        'Orlando Bloom',
        'Peter O\'Toole',
        'Reese Witherspoon',
        'Elizabeth Taylor',
        'Shia LaBeouf',
        'Burt Lancaster',
        'Toshiro Mifune',
        'Michael Douglas',
        'Kevin Costner',
        'Alec Guinness',
        'Joe Pesci',
        'Helena Bonham Carter',
        'Emma Thompson',
        'Mark Wahlberg',
        'Orson Welles',
        'Sidney Poitier',
        'Keira Knightley',
        'Diane Keaton',
        'Halle Berry',
        'Grace Kelly',
    )

    athletes = (
        'Michael Jordan',
        'Tiger Woods',
        'Muhammed Ali',
        'Babe Ruth',
        'Wayne Gretzky',
        'Roger Federer',
        'Michael Phelps',
        'Pele',
        'Lance Armstrong',
        'Usain Bolt',
        'Donald Bradman',
        'Jim Thorpe',
        'Kobe Bryant',
        'Jim Brown',
        'Jerry Rice',
        'Lebron James',
        'Wilt Chamberlain',
        'Joe Montana',
        'Diego Maradona',
        'Carl Lewis',
        'Bo Jackson',
        'Earvin "Magic" Johnson',
        'Michael Schumacher',
        'Barry Sanders',
        'Jesse Owens',
        'Larry Bird',
        'Willie Mays',
        'Brett Favre',
        'Walter Payton',
        'Peyton Manning',
        'Pete Sampras',
        'Jack Nicklaus',
        'Pete Rose',
        'Hank Aaron',
        'Mickey Mantle',
        'Lou Gehrig',
        'Mike Tyson',
        'Mario Lemieux',
        'Deion Sanders',
        'Barry Bonds',
        'Ty Cobb',
        'Jackie Robinson',
        'Tom Brady',
        'Secretariat',
        'Michael Johnson',
        'Albert Pujols',
        'Nadia Comaneci',
        'Mark Spitz',
        'Kareem Abdul Jabar',
        'David Beckham',
        'Rafael Nadal',
        'Cristiano Ronaldo',
        'Bill Russell',
        'Ted Williams',
        'Venus Williams',
        'Rocky Marciano',
        'Johnny Unitas',
        'Alex Rodriguez',
        'Dan Marino',
        'Lionel Messi',
        'Serena Williams',
        'Steffi Graf',
        'Derek Jeter',
        'Ronaldo Luis Nazario de Lima',
        'Babe Didrikson',
        'Steve Nash',
        'John Elway',
        'Joe DiMaggio',
        'Rod Laver',
        'Manny Pacquiao',
        'Shaquille O\'Neal',
        'Sachin Tendulkar',
        'Zinedine Zidane',
        'Bobby Orr',
        'Martina Navratilova',
        'Ken Griffey Jr.',
        'Cy Young',
        'Randy Moss',
        'Nolan Ryan',
        'Oscar Robertson',
        'Bruce Lee',
        'George Best',
        'Paavo Nurmi',
        'Gordie Howe',
        'Valentino Rossi',
        'Dale Earnhardt',
        'Tim Duncan',
        'Sugar Ray Robinson',
        'Sidney Crosby',
        'Ian Thorpe',
        'Richard Petty',
        'Jeff Gordon',
        'Steve Redgrave',
        'Haile Gebrselassie',
        'Joe Louis',
        'Alexander Karelin',
        'Emil Zatopek',
        'Adrian Peterson',
        'O.J. Simpson',
        'Fedor Emelianenko'
    )

    apps = (
        'Facebook',
        'Angry Birds',
        'Shazam',
        'Doodle Jump',
        'Pocket God',
        'Paper Toss',
        'Pandora',
        'Urbanspoon',
        'Kindle',
        'Flight Control',
        'Skype',
        'Monopoly',
        'Tetris',
        'Twitter',
        'IMDb',
        'Jelly Car',
        'Fieldrunners',
        'Cut the Rope',
        'Bejeweled 2',
        'Red Laser',
        'Tap Tap Revenge',
        'Cube Runner',
        'Stanza',
        'Scrabble',
        'SoundHound'
    )

    movies = (
        'The Godfather',
        'The Shawshank Redemption',
        'Titanic',
        'Casablanca',
        'Forrest Gump',
        'The Lord of the Rings: The Return of the King',
        'Pulp Fiction',
        'Gone with the Wind',
        'Schindler\'s List',
        'The Dark Knight',
        'The Godfather Part II',
        'Star Wars',
        'Goodfellas',
        'Saving Private Ryan',
        'Fight Club',
        'Citizen Kane',
        'Braveheart',
        'The Lord of the Rings: The Fellowship of the Ring',
        'Gladiator',
        'It\'s A Wonderful Life',
        'The Wizard of Oz',
        'The Departed',
        'The Sound of Music',
        'The Lord of the Rings: The Two Towers',
        'Scarface',
        '2001: A Space Odyssey',
        'One Flew Over the Cuckoo\'s Nest',
        'The Good, The Bad, and The Ugly',
        'The Matrix',
        'American Beauty',
        'Avatar',
        'Apocalypse Now',
        'The Notebook',
        'Raiders of the Lost Ark',
        'Lawrence of Arabia',
        'Taxi Driver',
        'The Silence of the Lambs',
        'A Beautiful Mind',
        'Ben Hur',
        'A Clockwork Orange',
        'Psycho',
        'The Shining',
        'Back to the Future',
        'Jaws',
        'Rocky',
        'Memento',
        'To Kill A Mockingbird',
        'No Country for Old Men',
        'American History X',
        'Singin\' in the Rain',
        'Alfred Hitchcock\'s Rear Window',
        'The Usual Suspects',
        'Pride and Prejudice',
        'Slumdog Millionaire',
        'The Empire Strikes Back',
        'The Green Mile',
        'Troy',
        'Terminator 2: Judgement Day',
        'Blade Runner',
        'The Big Lebowski',
        'Vertigo',
        'Reservoir Dogs',
        'Eternal Sunshine of the Spotless Mind',
        'On the Waterfront',
        'Dr. Strangelove',
        'The Seven Samurai',
        '8 1/2',
        'Life is Beautiful',
        'Amadeus',
        'Die Hard',
        'Annie Hall',
        'Monty Python and the Holy Grail',
        'The Ten Commandments',
        'Twilight',
        'Amalie',
        'Alien',
        'The Pianist',
        'The Sting',
        'Crash',
        'Se7en',
        'Jurassic Park',
        'Platoon',
        'Unforgiven',
        'The Sixth Sense',
        'Pirates of the Caribbean: The Curse of the Black Pearl',
        'Butch Cassidy and the Sundance Kid',
        'There Will Be Blood',
        'Dances with Wolves',
        'Scent of a Woman',
        'The Princess Bride',
        'Grease',
        'Breakfast at Tiffany\'s',
        'Cool Hand Luke',
        'My Fair Lady',
        'The Lion King',
        'Heat',
        '12 Angry Men',
        'Rain Man',
        'The Graduate',
        'The Bridge on the River Kwai',
    )

    video_games = (
        'The Legend of Zelda: Ocarina of Time',
        'Halo',
        'Call of Duty 4: Modern Warfare',
        'Super Mario 64',
        'Final Fantasy VII',
        'Super Mario Brothers',
        'Halo 3',
        'Grand Theft Auto IV',
        'BioShock',
        'GoldenEye 007',
        'Fallout 3',
        'Halo 2',
        'Tetris',
        'Pac-Man',
        'World of Warcraft',
        'Half-Life 2',
        'Grand Theft Auto: San Andreas',
        'Super Mario Brothers 3',
        'Call of Duty: Modern Warfare 2',
        'Guitar Hero',
        'Metal Gear Solid',
        'Gears of War',
        'Assassin\'s Creed',
        'Starcraft',
        'Super Mario World',
        'Mario Kart',
        'The Elder Scrolls IV: Oblivion',
        'Resident Evil 4',
        'Diablo 2',
        'God of War',
        'Final Fantasy X',
        'Star Wars: Knights of the Old Republic',
        'Half-Life',
        'The Legend of Zelda',
        'Super Smash Bros. Brawl',
        'Super Mario Galaxy',
        'Grand Theft Auto 3',
        'Warcraft III: Reign of Chaos',
        'The Legend of Zelda: A Link to the Past',
        'Sonic the Hedgehog',
        'The Sims',
        'Super Metroid',
        'Mortal Kombat',
        'Call of Duty: World at War',
        'Final Fantasy VIII',
        'Donkey Kong',
        'Doom',
        'Red Dead Redemption',
        'Chrono Trigger',
        'Mario Party',
        'Rock Band',
        'Mario Kart 64',
        'Shadow of the Colossus',
        'Super Smash Bros Melee',
        'Metal Gear Solid 4: Guns of the Patriots',
        'Mass Effect',
        'Deus Ex',
        'Kingdom Hearts',
        'Gears of War 2',
        'Mass Effect 2',
        'Final Fantasy Vi',
        'Resident Evil',
        'Assasins Creed 2',
        'Age of Mythology',
        'Portal',
        'Pokemon Red and Blue',
        'The Legend of Zelda: Majora\'s Mask',
        'Star Wars: Battlefront II',
        'Super Smash Brothers',
        'Call of Duty',
        'Paper Mario',
        'Metal Gear Solid 3',
        'Batman: Arkham Asylum',
        'Age of Empires 2',
        'Street Fighter',
        'Grand Theft Auto: Vice City',
        'God of War 3',
        'Mega Man 2',
        'Counter Strike',
        'Resident Evil 5',
        'The Legend of Zelda: Twilight Princess',
        'Street Fighter 2',
        'Uncharted 2: Among Thieves',
        'Saints Row 2',
        'Need for Speed: Most Wanted',
        'Age of Empires',
        'Resident Evil 2',
        'Borderlands',
        'Silent Hill 2',
        'Space Invaders',
        'God of War 2',
        'Contra',
        'Silent Hill',
        'Grand Theft Auto',
        'Grand Torisimo',
        'Heroes of Might & Magic 3',
        'Dead Space',
        'Donkey Kong Country',
        'Fable 2',
        'Diablo'
    )

    television_shows = (
        'Friends',
        'Seinfeld',
        'The Simpsons',
        'Family Guy',
        'Lost',
        'M*A*S*H',
        'House',
        'South Park',
        'I Love Lucy',
        'The Office',
        'Cheers',
        'Scrubs',
        'Dexter',
        'Arrested Development',
        'The Twilight Zone',
        'The Sopranos',
        'Grey\'s Anatomy',
        'All in the Family',
        'Buffy the Vampire Slayer',
        'Saturday Night Live',
        'Supernatural',
        'The Big Bang Theory',
        'That 70s Show',
        'Star Trek',
        '24',
        'Two and a Half Men',
        'American Idol',
        'How I Met Your Mother',
        'The X Files',
        'Heroes',
        'Sex and the City',
        'Glee',
        'NCIS',
        'Desperate Housewives',
        'Law and Order',
        'Entourage',
        'Bones',
        'The Wire',
        'True Blood',
        'Angel',
        '30 Rock',
        'Frasier',
        'Gilmore Girls',
        'Survivor',
        'Monk',
        'Firefly',
        'The Andy Griffith Show',
        'The Cosby Show',
        'ER',
        'Smallville',
        'SpongeBob SquarePants',
        'CSI: Crime Scene Investigation',
        'The Golden Girls',
        'Everybody Loves Raymond',
        'Doctor Who',
        'The Fresh Prince of Bel-Air',
        'Curb Your Enthusiasm',
        'Criminal Minds',
        'Six Feet Under',
        'Happy Days',
        'Jeopardy',
        'Futurama',
        'Modern Family',
        'Bonanza',
        'Prison Break',
        'Law and Order SVU',
        'Gunsmoke',
        'Columbo',
        'Mad Men',
        'Weeds',
        'Fawlty Towers',
        'King of Queens',
        'Gossip Girl',
        'The West Wing',
        'Hill Street Blues',
        'King of the Hill',
        'Twin Peaks',
        'Malcolm in the Middle',
        'Monty Python\'s Flying Circus',
        'The Wonder Years',
        'Star Trek: The Next Generation',
        'Psych',
        'Home Improvement',
        'Three\'s Company',
        'The Flintstones',
        'CSI: New York',
        'Will & Grace',
        'American Dad',
        'Charmed',
        'It\'s Always Sunny in Philadelphia',
        'Sesame Street',
        'Mythbusters',
        'Veronica Mars',
        'Freaks and Geeks',
        'Gilligan\'s Island',
        'NYPD Blue',
        'One Tree Hill',
        'Battlestar Galactica',
        'Dawson\'s Creek',
        'SportsCenter'
    )
